// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Persistence.Migrations
{
  [DbContext(typeof(DataDbContext))]
  [Migration("20201214142718_initial")]
  partial class initial
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "3.1.10");

      modelBuilder.Entity("Domain.Models.Activity", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("TEXT");

            b.Property<string>("Category")
                      .HasColumnType("TEXT");

            b.Property<string>("City")
                      .HasColumnType("TEXT");

            b.Property<DateTime>("Date")
                      .HasColumnType("TEXT");

            b.Property<string>("Description")
                      .HasColumnType("TEXT");

            b.Property<string>("Title")
                      .HasColumnType("TEXT");

            b.Property<string>("Venue")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("Activities");
          });
#pragma warning restore 612, 618
    }
  }
}
